# Site info
title = "InfluxDB"
baseurl = "http://influxdb.com/"

# Site configuration
languageCode = "en-US"
config = "config.toml"
publishdir = "public"
contentdir = "content"
layoutdir = "layouts"

# Site links
[permalinks]
  post = "/:year/:month/:title/"
  site = "/:filename/"
#  docs = "/:section/"