# Site info
title = "InfluxDB"
baseurl = "http://new.influxdb.com/"

# Site configuration
languageCode = "en-US"
config = "config.toml"
publishdir = "public"
contentdir = "content"
layoutdir = "layouts"

# Use urls that end in .html
uglyurls = true

# Site links
[permalinks]
  # blog = "/:section/:year/:month/:day/:slug.html"
  site = "/:filename/index.html"

#[taxonomies]
#  version = "versions"